name: Deploy to DigitalOcean

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Trigger the workflow on push or pull request to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t shiboka.com .

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker image to GitHub Container Registry
      run: docker tag shiboka.com:latest ghcr.io/${{ github.repository_owner }}/shiboka.com:latest && docker push ghcr.io/${{ github.repository_owner }}/shiboka.com:latest

    - name: SSH and deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: root
        key: ${{ secrets.DROPLET_SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
        script: |
          echo "${{ secrets.GH_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
          docker pull ghcr.io/${{ github.repository_owner }}/shiboka.com:latest
          docker stop shiboka.com || true
          docker rm shiboka.com || true
          docker run -d -p 80:80 --name shiboka.com ghcr.io/${{ github.repository_owner }}/shiboka.com:latest